### ISSUE TITLE
No attribute 'forecast' inside ForecastIO

### ISSUE THREAD

**Issue by OlafSzmidt** [dvdme/forecastiopy#6]
Traceback (most recent call last):
      File "/home/olaf/.local/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
        return self.wsgi_app(environ, start_response)
      File "/home/olaf/.local/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
        response = self.make_response(self.handle_exception(e))
      File "/home/olaf/.local/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/olaf/.local/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/olaf/.local/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/olaf/.local/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/olaf/.local/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/olaf/.local/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/olaf/Hackathons/Brumhack5/BrumHack5/jasien.py", line 49, in checkStuff
        weatherResult = getWeather(message_body_split[1])
      File "/home/olaf/Hackathons/Brumhack5/BrumHack5/jasien.py", line 26, in getWeather
        current = FIOCurrently.FIOCurrently(fio)
      File "/usr/local/lib/python2.7/dist-packages/forecastiopy/FIOCurrently.py", line 25, in __init__
        if forecast_io.has_currently():
      File "/usr/local/lib/python2.7/dist-packages/forecastiopy/ForecastIO.py", line 185, in has_currently
        return 'currently' in self.forecast
    AttributeError: 'ForecastIO' object has no attribute 'forecast'

**Comment by dvdme** [comment]
It seams like the `fio` is not properly initialized. Did you set the api key, latitude and longitude properly?

This how it shoud be done:

```python
fio = ForecastIO.ForecastIO('a66c3d9fd49043109081f945a9d4abba', latitude=38.725, longitude=-9.15)
 cur = FIOCurrently.FIOCurrently(fio)
```

**Comment by OlafSzmidt** [comment]
That's exactly how it was done. I'm no longer building the code so I presume I may close this issue, but look into it perhaps.
